# Ref: https://docs.docker.jp/compose/rails.html#id2
version: '3'
services:
  app:
    container_name: my-portfolio
    image: node:22
    ports:
      - 3000:80
    # See https://amateur-engineer-blog.com/docer-compose-volumes/
    volumes:
      - type: bind
        source: '..'
        target: '/workspace/app'
    tty: true # See https://zenn.dev/hohner/articles/43a0da20181d34
    stdin_open: true
    # restart: always
